name: Create GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag message
        id: tag-message
        run: |
          {
            echo 'body<<EOF'
            git tag -l --format='%(contents)' '${{ github.ref_name }}'
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.tag-message.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
